version : "3.6"


services:

  web :
    build : .
    volumes :
      - ./src:/src/
    container_name: "fast_api_web"
    ports :
      - 8000:8000
    env_file : .env
    depends_on :
      - db
    restart : on-failure

  db:
    image : postgres:13.7
    volumes : 
      - postgres_data:/var/lib/postgresql/data/
    ports : 
      - 5432:5432
    environment :
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=admin
      - POSTGRES_DB=fastapi_dev

volumes:
  postgres_data:


  